E2Helper.Descriptions["spriteSpawn(nsvvnnenn)"] = "Creates a Sprite, takes: index, path (string), position (vector), color (vector), alpha, scale, parent (entity), rendermode and framerate"
E2Helper.Descriptions["spriteSpawn(n)"] = "Creates a Sprite of the given index"
E2Helper.Descriptions["spriteEnable(nn)"] = "Toggles the state of the sprite of the given index (On/Off)"
E2Helper.Descriptions["spriteSetPos(nv)"] = "Sets the position of the sprite at the given index"
E2Helper.Descriptions["spriteSetColor(nv)"] = "Sets the color of the sprite at the given index"
E2Helper.Descriptions["spriteSetAlpha(nn)"] = "Sets the opacity of the sprite at the given index"
E2Helper.Descriptions["spriteSetScale(nn)"] = "Sets the scale of the sprite at the given index"
E2Helper.Descriptions["spriteSetParent(ne)"] = "Sets the parent of the sprite at the given index"
E2Helper.Descriptions["spriteSetRendermode(nn)"] = "Sets the rendermode of the sprite at the given index (3 = World Glow, 9 = Glow"
E2Helper.Descriptions["spriteSetFramerate(nn)"] = "Sets the framerate of the sprite at the given index"
E2Helper.Descriptions["spriteList"] = "Prints on chat the list of avaliable sprites."
E2Helper.Descriptions["spriteRList"] = "Prints on chat the list of avaliable render modes."
